## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
	all_modules = [mod[len("ns3-"):] for mod in bld.env['NS3_ENABLED_MODULES'] + bld.env['NS3_ENABLED_CONTRIBUTED_MODULES']]
	obj = bld.create_ns3_program('first-netanim', all_modules)
	obj.source = 'first-netanim.cc'
	obj = bld.create_ns3_program('first-ascii-tracer', all_modules)
	obj.source = 'first-ascii-tracer.cc'
	obj = bld.create_ns3_program('OnOffStar', all_modules)
	obj.source = 'OnOffStar.cc'
	obj = bld.create_ns3_program('bulk-send', all_modules)
	obj.source = 'bulk-send.cc'
	obj = bld.create_ns3_program('udp-echo', all_modules)
	obj.source = 'udp-echo.cc'
    # obj = bld.create_ns3_program('energy-model-with-harvesting-example', ['core', 'mobility', 'wifi', 'energy', 'internet', 'config-store'])
    # obj.source = 'energy-model-with-harvesting-example.cc'
